---
- name: Configure NTP sync
  hosts: all
  become: yes
  tasks:
    - name: Install ntpdate and ntp (Ubuntu)
      apt:
        name: [ 'ntpdate', 'ntp' ]
        state: present
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install chrony (RHEL)
      yum:
        name: chrony
        state: present
      when: ansible_facts['distribution'] == 'RedHat' or ansible_facts['distribution'] == 'CentOS'

    - name: Enable and start ntp service (Ubuntu)
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Enable and start chronyd service (RHEL)
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_facts['distribution'] == 'RedHat' or ansible_facts['distribution'] == 'CentOS'

